# """Changed column id to str from int

# Revision ID: cb7eaac43643
# Revises: 4e2ee9a0bb57
# Create Date: 2025-12-22 21:24:10.908498

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'cb7eaac43643'
# down_revision: Union[str, Sequence[str], None] = '4e2ee9a0bb57'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('admins', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('admins', 'user_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('guests', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('guests', 'user_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('roles', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False,
#                existing_server_default=sa.text("nextval('roles_id_seq'::regclass)"))
#     op.alter_column('users', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('users', 'role_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'role_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('users', 'id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('roles', 'id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False,
#                existing_server_default=sa.text("nextval('roles_id_seq'::regclass)"))
#     op.alter_column('guests', 'user_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('guests', 'id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('admins', 'user_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('admins', 'id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     # ### end Alembic commands ###









"""Changed column id to str from int

Revision ID: cb7eaac43643
Revises: 4e2ee9a0bb57
Create Date: 2025-12-22 21:24:10.908498
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7eaac43643'
down_revision = '4e2ee9a0bb57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1️⃣ Drop FKs
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.drop_constraint("admins_user_id_fkey", "admins", type_="foreignkey")
    op.drop_constraint("guests_user_id_fkey", "guests", type_="foreignkey")

    # 2️⃣ Alter PKs first
    op.alter_column(
        'roles', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="id::varchar",
        existing_nullable=False
    )
    op.alter_column(
        'users', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="id::varchar",
        existing_nullable=False
    )
    op.alter_column(
        'admins', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="id::varchar",
        existing_nullable=False
    )
    op.alter_column(
        'guests', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="id::varchar",
        existing_nullable=False
    )

    # 3️⃣ Alter FK columns
    op.alter_column(
        'users', 'role_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="role_id::varchar",
        existing_nullable=False
    )
    op.alter_column(
        'admins', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="user_id::varchar",
        existing_nullable=False
    )
    op.alter_column(
        'guests', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="user_id::varchar",
        existing_nullable=False
    )

    # 4️⃣ Recreate FKs
    op.create_foreign_key("users_role_id_fkey", "users", "roles", ["role_id"], ["id"])
    op.create_foreign_key("admins_user_id_fkey", "admins", "users", ["user_id"], ["id"])
    op.create_foreign_key("guests_user_id_fkey", "guests", "users", ["user_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema safely."""
    # Drop FK constraints first
    op.drop_constraint("admins_user_id_fkey", "admins", type_="foreignkey")
    op.drop_constraint("guests_user_id_fkey", "guests", type_="foreignkey")

    # Alter foreign key columns back
    op.alter_column(
        'admins', 'user_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="user_id::integer",
        existing_nullable=False
    )

    op.alter_column(
        'users', 'role_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="role_id::integer",
        existing_nullable=False
    )

    op.alter_column(
        'guests', 'user_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="user_id::integer",
        existing_nullable=False
    )

    # Alter PK columns back
    op.alter_column(
        'users', 'id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="id::integer",
        existing_nullable=False
    )

    op.alter_column(
        'roles', 'id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="id::integer",
        existing_nullable=False
    )

    op.alter_column(
        'admins', 'id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="id::integer",
        existing_nullable=False
    )

    op.alter_column(
        'guests', 'id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="id::integer",
        existing_nullable=False
    )

    # Recreate FK constraints
    op.create_foreign_key(
        "admins_user_id_fkey",
        "admins", "users",
        ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "guests_user_id_fkey",
        "guests", "users",
        ["user_id"], ["id"]
    )
